name: 🤖 Auto Comment on Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: 💬 Add Comment to Issue
        run: |
          COMMENT=$(cat <<EOF
          {
            "body": "🎉 Thank you for raising this issue in the **🎮 Movie-to-Music Recommendation System 🎵** repository! We're thrilled to have your input. 😊\n\nPlease make sure this [issue](https://github.com/androidvitb/MovMusic/issues) is not a duplicate and that you've reviewed the [CONTRIBUTING.md](https://github.com/androidvitb/MovMusic/blob/Main/CONTRIBUTING.md) guide. Your contributions help us improve the project, and we deeply appreciate your effort! 🚀"
          }
          EOF
          )
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d "$COMMENT")
          cat response.json
          if [ "$RESPONSE" -ne 201 ]; then
            echo "❌ Failed to add comment"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
